### ISSUE TITLE
gurobi download/installation out of date

### ISSUE THREAD

**Issue by mposa** [RobotLocomotion/drake-distro#11]
The gurobi website has changed somewhat, so the login page is now: http://www.gurobi.com/login and the download page is http://user.gurobi.com/download/gurobi-optimizer.

However, more importantly, 5.6.2 is no longer available on the website. I changed the download_gurobi script to reflect the new versions and URLs, but something deeper inside the make process is still assuming 5.6.2.

**Comment by RussTedrake** [comment]
Thanks.  There is already an issue on this in drake.  Will update it soon.
