### ISSUE TITLE
snopt and sedumi pods broken?

### ISSUE THREAD

**Issue by sheim** [RobotLocomotion/drake-distro#14]
Both Snopt and Sedumi pods lead to 404 pages...?

**Comment by RussTedrake** [comment]
yes — they are password protected because i do not want to violate the licenses.   sedumi is free, but you should download it through their website.  snopt requires a paid license.

- Russ

**Comment by sheim** [comment]
Gotcha. I thought the pods had just wrappers, not the actual library.
Cheers
