### ISSUE TITLE
Submodule bertini deleted ?

### ISSUE THREAD

**Issue by SyrianSpock** [RobotLocomotion/drake-distro#16]
I have been trying to clone the repository, but the `bertini` submodule seems to be inexistant. 
Has it been deleted ?

**Comment by RussTedrake** [comment]
Perhaps you are trying to clone master, which requires some extra permissions.  (bertini is free, but the license prevents me from redistributing it).   The rigidbody branch is recommended for most people.

As the number of external users has grown, it might be time for me to flip this: make master act like rigidbody and have a separate, non-master branch for local folks.

- Russ

**Comment by SyrianSpock** [comment]
Thanks a lot.
